# Generated by Django 6.0.4 on 2026-05-06 00:34

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplyRule',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human-readable name e.g. 'Pricing Enquiry Reply'", max_length=255)),
                ('keyword', models.CharField(blank=True, default='', help_text='The trigger keyword or pattern. Leave blank for fallback rules.', max_length=255)),
                ('match_type', models.CharField(choices=[('exact', 'Exact Match'), ('contains', 'Contains Keyword'), ('startswith', 'Starts With'), ('regex', 'Regular Expression')], default='contains', max_length=20)),
                ('reply_text', models.TextField(help_text='The message text to send when this rule matches.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_fallback', models.BooleanField(default=False, help_text='If True, this rule fires when no other rule matches.')),
                ('priority', models.PositiveIntegerField(default=10, help_text='Lower number = evaluated first. Range: 1 (highest) to 100 (lowest).')),
                ('trigger_count', models.PositiveIntegerField(default=0, editable=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_reply_rules', to='whatsapp_integration.businessaccount')),
            ],
            options={
                'db_table': 'auto_reply_rules',
                'ordering': ['priority', 'created_at'],
            },
        ),
    ]
