# Generated by Django 6.0.4 on 2026-05-06 10:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0002_autoreplyrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAttachment',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('document', 'Document'), ('sticker', 'Sticker')], max_length=20)),
                ('media_url', models.URLField(blank=True, default='', help_text='Provider-hosted URL for the media file', max_length=2048)),
                ('provider_media_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('mime_type', models.CharField(blank=True, default='', help_text='e.g. image/jpeg, audio/ogg, application/pdf', max_length=127)),
                ('file_name', models.CharField(blank=True, default='', help_text='Original filename for documents', max_length=255)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes', null=True)),
                ('caption', models.TextField(blank=True, default='', help_text='Optional caption sent with the media')),
                ('stored_url', models.URLField(blank=True, default='', help_text='Our own stored copy URL (e.g. S3). Empty if not downloaded.', max_length=2048)),
                ('is_downloaded', models.BooleanField(default=False)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='media_attachment', to='whatsapp_integration.message')),
            ],
            options={
                'db_table': 'media_attachments',
                'ordering': ['-created_at'],
            },
        ),
    ]
