# Generated by Django 6.0.4 on 2026-05-06 13:20

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0003_mediaattachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Internal name e.g. 'Order Confirmation'", max_length=255)),
                ('template_name', models.CharField(help_text="Provider template name e.g. 'order_confirmation' (snake_case)", max_length=512)),
                ('category', models.CharField(choices=[('marketing', 'Marketing'), ('utility', 'Utility'), ('authentication', 'Authentication')], default='utility', max_length=30)),
                ('language', models.CharField(choices=[('en', 'English'), ('en_US', 'English (US)'), ('sw', 'Swahili'), ('fr', 'French'), ('ar', 'Arabic'), ('es', 'Spanish'), ('pt_BR', 'Portuguese (Brazil)')], default='en', max_length=10)),
                ('body', models.TextField(help_text='Template body with {{1}}, {{2}} placeholders')),
                ('header_text', models.CharField(blank=True, default='', max_length=60)),
                ('header_media_url', models.URLField(blank=True, default='', max_length=2048)),
                ('footer_text', models.CharField(blank=True, default='', max_length=60)),
                ('variable_count', models.PositiveIntegerField(default=0, editable=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paused', 'Paused'), ('disabled', 'Disabled')], default='draft', max_length=20)),
                ('provider_template_id', models.CharField(blank=True, default='', max_length=255)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('send_count', models.PositiveIntegerField(default=0, editable=False)),
                ('success_count', models.PositiveIntegerField(default=0, editable=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='whatsapp_integration.businessaccount')),
            ],
            options={
                'db_table': 'message_templates',
                'ordering': ['-created_at'],
                'unique_together': {('business', 'template_name', 'language')},
            },
        ),
        migrations.CreateModel(
            name='TemplateSend',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variables', models.JSONField(default=list)),
                ('rendered_body', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('error_message', models.TextField(blank=True, default='')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_sends', to='whatsapp_integration.whatsappcontact')),
                ('message', models.OneToOneField(blank=True, help_text='The Message record created when this template was sent', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_send', to='whatsapp_integration.message')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sends', to='whatsapp_integration.messagetemplate')),
            ],
            options={
                'db_table': 'template_sends',
                'ordering': ['-created_at'],
            },
        ),
    ]
