# Generated by Django 6.0.4 on 2026-05-07 07:21

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0004_messagetemplate_templatesend'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human label e.g. 'CRM Integration' or 'Analytics Pipeline'", max_length=255)),
                ('url', models.URLField(help_text='HTTPS endpoint that will receive event POST requests', max_length=2048)),
                ('secret', models.CharField(help_text='Secret key used to sign webhook payloads', max_length=255)),
                ('subscribed_events', models.JSONField(default=list, help_text='List of event types this endpoint will receive')),
                ('is_active', models.BooleanField(default=True)),
                ('total_deliveries', models.PositiveIntegerField(default=0, editable=False)),
                ('failed_deliveries', models.PositiveIntegerField(default=0, editable=False)),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_endpoints', to='whatsapp_integration.businessaccount')),
            ],
            options={
                'db_table': 'webhook_endpoints',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookDeliveryLog',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('payload', models.JSONField(help_text='Full event payload sent')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('retrying', 'Retrying')], default='pending', max_length=20)),
                ('http_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_body', models.TextField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('attempt_number', models.PositiveIntegerField(default=1)),
                ('duration_ms', models.PositiveIntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('endpoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='whatsapp_integration.webhookendpoint')),
            ],
            options={
                'db_table': 'webhook_delivery_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
