# Generated by Django 6.0.4 on 2026-05-08 00:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0005_webhookendpoint_webhookdeliverylog'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Human label e.g. 'Production App Key' or 'CI/CD Pipeline'", max_length=255)),
                ('prefix', models.CharField(editable=False, help_text='First characters of the raw key for identification', max_length=16)),
                ('key_hash', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('scope', models.CharField(choices=[('read', 'Read Only'), ('write', 'Read + Write'), ('admin', 'Full Admin')], default='write', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('revoked', 'Revoked'), ('expired', 'Expired')], default='active', max_length=10)),
                ('expiry_at', models.DateTimeField(blank=True, help_text='Optional expiry. Null = never expires.', null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('allowed_ips', models.JSONField(blank=True, default=list, help_text='Optional list of allowed IP addresses. Empty = all IPs allowed.')),
                ('request_count', models.PositiveBigIntegerField(default=0, editable=False, help_text='Total number of requests made with this key')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='whatsapp_integration.businessaccount')),
                ('rotated_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotated_to', to='whatsapp_integration.apikey')),
            ],
            options={
                'db_table': 'api_keys',
                'ordering': ['-created_at'],
            },
        ),
    ]
