# Generated by Django 6.0.4 on 2026-05-08 01:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsapp_integration', '0006_apikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('online', 'Online'), ('away', 'Away'), ('offline', 'Offline')], default='online', max_length=10)),
                ('max_conversations', models.PositiveIntegerField(default=10, help_text='Maximum open conversations this agent can handle at once')),
                ('last_assigned_at', models.DateTimeField(blank=True, help_text='Used for round-robin ordering — least recently assigned goes first', null=True)),
                ('total_assigned', models.PositiveIntegerField(default=0, editable=False)),
                ('total_resolved', models.PositiveIntegerField(default=0, editable=False)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='whatsapp_integration.businessaccount')),
            ],
            options={
                'db_table': 'agents',
                'ordering': ['name'],
                'unique_together': {('business', 'email')},
            },
        ),
        migrations.CreateModel(
            name='AssignmentLog',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_by', models.CharField(blank=True, default='system', help_text="Who triggered this assignment (agent email or 'system')", max_length=255)),
                ('assignment_type', models.CharField(choices=[('auto', 'Auto (Round-Robin)'), ('manual', 'Manual')], default='auto', max_length=10)),
                ('unassigned_at', models.DateTimeField(blank=True, null=True)),
                ('unassignment_reason', models.CharField(blank=True, default='', max_length=255)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignment_logs', to='whatsapp_integration.agent')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_logs', to='whatsapp_integration.conversation')),
            ],
            options={
                'db_table': 'assignment_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Label name e.g. 'urgent', 'billing', 'vip'", max_length=50)),
                ('colour', models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('pink', 'Pink'), ('grey', 'Grey')], default='blue', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labels', to='whatsapp_integration.businessaccount')),
            ],
            options={
                'db_table': 'labels',
                'ordering': ['name'],
                'unique_together': {('business', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ConversationLabel',
            fields=[
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('applied_by', models.CharField(blank=True, default='', help_text='Agent name or API key prefix that applied this label', max_length=255)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_labels', to='whatsapp_integration.conversation')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_labels', to='whatsapp_integration.label')),
            ],
            options={
                'db_table': 'conversation_labels',
                'ordering': ['-created_at'],
                'unique_together': {('conversation', 'label')},
            },
        ),
    ]
